{
 "title": "Dnsdist",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(dnsdist_cache_hits,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Time to answer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(dnsdist_latency0_1{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "<1ms"
    },
    {
     "expr": "sum(increase(dnsdist_latency1_10{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "1-10ms"
    },
    {
     "expr": "sum(increase(dnsdist_latency10_50{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "10-50ms"
    },
    {
     "expr": "sum(increase(dnsdist_latency50_100{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "50-100ms"
    },
    {
     "expr": "sum(increase(dnsdist_latency100_1000{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "100ms-1s"
    },
    {
     "expr": "sum(increase(dnsdist_latency_slow{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": ">1s"
    }
   ]
  },
  {
   "title": "Backend queries issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(dnsdist_downstream_timeouts{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "timeouts"
    },
    {
     "expr": "sum(increase(dnsdist_downstream_send_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(increase(dnsdist_noncompliant_responses{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "non-compliant"
    },
    {
     "expr": "sum(increase(dnsdist_servfail_responses{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "servfail"
    },
    {
     "expr": "sum(increase(dnsdist_server_outstanding{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "outstanding"
    }
   ]
  },
  {
   "title": "Packet queries vs responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(dnsdist_queries{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "queries"
    },
    {
     "expr": "sum(increase(dnsdist_responses{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "responses"
    }
   ]
  },
  {
   "title": "Rule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(dnsdist_rule_drop{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "drop"
    },
    {
     "expr": "sum(increase(dnsdist_rule_nxdomain{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "nxdomain"
    },
    {
     "expr": "sum(increase(dnsdist_rule_refused{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "refused"
    },
    {
     "expr": "sum(increase(dnsdist_rule_servfail{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "servfail"
    },
    {
     "expr": "sum(increase(dnsdist_rule_truncated{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "truncated"
    }
   ]
  },
  {
   "title": "Dynamic block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(dnsdist_dyn_blocked{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "blocked"
    },
    {
     "expr": "sum(increase(dnsdist_dyn_block_nmg_size{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "entries"
    }
   ]
  },
  {
   "title": "Latency over last 100 packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(dnsdist_latency_avg100{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Queries protocol usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(dnsdist_frontend_queries{instance=~\"$instance\", proto=\"TCP\"}[$__rate_interval]))",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(increase(dnsdist_frontend_queries{instance=~\"$instance\", proto=\"UDP\"}[$__rate_interval]))",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(increase(dnsdist_frontend_queries{instance=~\"$instance\", proto=\"TCP (DNS over HTTPS)\"}[$__rate_interval]))",
     "legendFormat": "DoH"
    },
    {
     "expr": "sum(increase(dnsdist_frontend_queries{instance=~\"$instance\", proto=\"TCP (DNS over TLS)\"}[$__rate_interval]))",
     "legendFormat": "DoT"
    }
   ]
  },
  {
   "title": "Answer cache hits vs misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(dnsdist_cache_hits{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(increase(dnsdist_cache_misses{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "misses"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "$instance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsdist_server_status{instance=~\"$instance\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  }
 ]
}