{
 "title": "k8up",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(k8up_jobs_total,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Namespace", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 1 } },
  { "title": "Schedules jobs", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 2, "y": 1 } },
  { "title": "Total failed jobs", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 4, "y": 1 } },
  { "title": "Backup status", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 6, "y": 1 } },
  { "title": "Check status", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 9, "y": 1 } },
  { "title": "Archive status", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 12, "y": 1 } },
  { "title": "Restore status", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 15, "y": 1 } },
  { "title": "Prune status", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 18, "y": 1 } },
  { "title": "Schedule status", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 21, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "repeat": "exported_namespace",
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\r\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black;\"><p style=\"font-weight: bold;\">$namespace</p>\r\n  </td>\r\n</table>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8up_schedules_gauge{exported_namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8up_jobs_total - k8up_schedules_gauge",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "repeat": "namespace",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8up_jobs_successful_counter{exported_namespace=~\"$namespace\", jobType=\"backup\"} / k8up_jobs_total{exported_namespace=~\"$namespace\", jobType=\"backup\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "repeat": "namespace",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8up_jobs_successful_counter{exported_namespace=~\"$namespace\", jobType=\"check\"} / k8up_jobs_total{exported_namespace=~\"$namespace\", jobType=\"check\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "repeat": "namespace",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8up_jobs_successful_counter{exported_namespace=~\"$namespace\", jobType=\"archive\"} / k8up_jobs_total{exported_namespace=~\"$namespace\", jobType=\"archive\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "repeat": "namespace",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8up_jobs_successful_counter{exported_namespace=~\"$namespace\", jobType=\"restore\"} / k8up_jobs_total{exported_namespace=~\"$namespace\", jobType=\"restore\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "repeat": "namespace",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8up_jobs_successful_counter{exported_namespace=~\"$namespace\", jobType=\"prune\"} / k8up_jobs_total{exported_namespace=~\"$namespace\", jobType=\"prune\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "repeat": "namespace",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8up_jobs_successful_counter{exported_namespace=~\"$namespace\", jobType=\"schedule\"} / k8up_jobs_total{exported_namespace=~\"$namespace\", jobType=\"schedule\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Push Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Available snapshots per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "k8up_backup_restic_available_snapshots{instance=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Changed directories during backup per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "k8up_backup_restic_changed_directories_during_backup{instance=~\"$namespace\"}",
     "legendFormat": "{{instance}} - {{pvc}}"
    }
   ]
  },
  {
   "title": "Chnaged files during backup per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "k8up_backup_restic_changed_files_during_backup{instance=~\"$namespace\"}",
     "legendFormat": "{{instance}} - {{pvc}}"
    }
   ]
  },
  {
   "title": "Changed files during backup per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "k8up_backup_restic_changed_files_during_backup{instance=~\"$namespace\"}",
     "legendFormat": "{{instance}} - {{pvc}}"
    }
   ]
  },
  {
   "title": "New directories during backup per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "k8up_backup_restic_new_directories_during_backup{instance=~\"$namespace\"}",
     "legendFormat": "{{instance}} - {{pvc}}"
    }
   ]
  },
  {
   "title": "New directories during backup per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "k8up_backup_restic_new_directories_during_backup{instance=~\"$namespace\"}",
     "legendFormat": "{{instance}} - {{pvc}}"
    }
   ]
  },
  {
   "title": "Unmodified directories during backup per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "k8up_backup_restic_unmodified_directories_during_backup{instance=~\"$namespace\"}",
     "legendFormat": "{{instance}} - {{pvc}}"
    }
   ]
  },
  {
   "title": "Unmodified files during backup per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "k8up_backup_restic_unmodified_files_during_backup{instance=~\"$namespace\"}",
     "legendFormat": "{{instance}} - {{pvc}}"
    }
   ]
  }
 ]
}