{
 "title": "PowerDNS authoritative",
 "description": "Powerdns authoritative - https://www.powerdns.com/powerdns-authoritative-server",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(pdns_auth_cache_latency,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Packet queries vs responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_auth_udp_queries{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_auth_tcp_queries{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "queries"
    },
    {
     "expr": "sum(rate(pdns_auth_udp_answers{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_auth_tcp_answers{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "responses"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(pdns_auth_latency{instance=~\"$instance\"})",
     "legendFormat": "answer question"
    },
    {
     "expr": "sum(pdns_auth_receive_latency{instance=~\"$instance\"})",
     "legendFormat": "receive query"
    },
    {
     "expr": "sum(pdns_auth_send_latency{instance=~\"$instance\"})",
     "legendFormat": "send answer"
    }
   ]
  },
  {
   "title": "Recursion queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_auth_rd_queries{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(rate(pdns_auth_recursing_answers{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "answers"
    },
    {
     "expr": "sum(rate(pdns_auth_recursing_questions{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "questions"
    },
    {
     "expr": "sum(rate(pdns_auth_recursion_unanswered{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "unanswered"
    }
   ]
  },
  {
   "title": "Queries protocol usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_auth_tcp4_queries{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "TCP - IPv4"
    },
    {
     "expr": "sum(rate(pdns_auth_tcp6_queries{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "TCP - IPv4"
    },
    {
     "expr": "sum(rate(pdns_auth_udp4_queries{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "UDP - IPv4"
    },
    {
     "expr": "sum(rate(pdns_auth_udp6_queries{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "UDP - IPv6"
    }
   ]
  },
  {
   "title": "Packet cache hits vs misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_auth_packetcache_hit{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(rate(pdns_auth_packetcache_miss{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "UDP errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_auth_udp_in_csum_errors{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_auth_udp6_in_csum_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "in checksum"
    },
    {
     "expr": "sum(rate(pdns_auth_udp_in_errors{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_auth_udp6_in_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(pdns_auth_udp_noport_errors{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_auth_udp6_noport_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "noport"
    },
    {
     "expr": "sum(rate(pdns_auth_udp_recvbuf_errors{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_auth_udp6_recvbuf_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "recvbuf"
    },
    {
     "expr": "sum(rate(pdns_auth_udp_sndbuf_errors{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_auth_udp6_sndbuf_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "sndbuf"
    }
   ]
  },
  {
   "title": "Latency lookup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(pdns_auth_cache_latency{instance=~\"$instance\"})",
     "legendFormat": "cache"
    },
    {
     "expr": "sum(pdns_auth_backend_latency{instance=~\"$instance\"})",
     "legendFormat": "backend"
    }
   ]
  },
  {
   "title": "Incoming notifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_auth_incoming_notifications{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "notifications"
    }
   ]
  },
  {
   "title": "DNS update changes vs refused",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_auth_dnsupdate_changes{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "changes"
    },
    {
     "expr": "sum(rate(pdns_auth_dnsupdate_refused{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "refused"
    }
   ]
  },
  {
   "title": "DNS update queries vs answers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_auth_dnsupdate_queries{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "queries"
    },
    {
     "expr": "sum(rate(pdns_auth_dnsupdate_answers{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "answers"
    }
   ]
  },
  {
   "title": "Query cache hits vs misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_auth_query_cache_hit{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(rate(pdns_auth_query_cache_miss{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by (name) (pdns_auth_zone_cache_size{instance=~\"$instance\"})",
     "legendFormat": "zone"
    },
    {
     "expr": "sum by (name) (pdns_auth_key_cache_size{instance=~\"$instance\"})",
     "legendFormat": "key"
    },
    {
     "expr": "sum by (name) (pdns_auth_meta_cache_size{instance=~\"$instance\"})",
     "legendFormat": "meta"
    },
    {
     "expr": "sum by (name) (pdns_auth_signature_cache_size{instance=~\"$instance\"})",
     "legendFormat": "signature"
    },
    {
     "expr": "sum by (name) (pdns_auth_query_cache_size{instance=~\"$instance\"})",
     "legendFormat": "query"
    },
    {
     "expr": "sum by (name) (pdns_auth_packetcache_size{instance=~\"$instance\"})",
     "legendFormat": "packet"
    }
   ]
  }
 ]
}