{
 "title": "PowerDNS authoritative API",
 "description": "PowerDNS authoritative API with JSON exporter - https://www.powerdns.com/powerdns-authoritative-server",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(pdns_auth_api_response_by_qtype_value,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Qtype",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (rate(pdns_auth_api_response_by_qtype_value{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Qtype",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name) (rate(pdns_auth_api_response_by_qtype_value{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rcode",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (rate(pdns_auth_api_response_by_rcode_value{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rcode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (name) (rate(pdns_auth_api_response_by_rcode_value{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Response sizes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (name) (rate(pdns_auth_api_response_sizes_value{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}