{
 "title": "SNMP device",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(snmp_scrape_duration_seconds,instance)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(ifInOctets{instance=\"$instance\"},ifName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Interface status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ifPhysAddress{instance=\"$instance\",ifName=~\"$interface\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ifOperStatus{instance=\"$instance\",ifName=~\"$interface\"}"
    },
    {
     "expr": "ifHighSpeed{instance=\"$instance\",ifName=~\"$interface\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ifMtu{instance=\"$instance\",ifName=~\"$interface\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "scalar(sysUpTime{instance=\"$instance\"}) - ifLastChange{instance=\"$instance\",ifName=~\"$interface\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ifAdminStatus{instance=\"$instance\",ifName=~\"$interface\"}"
    }
   ]
  },
  { "title": "Interface throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(ifHCOutOctets{instance='$instance',ifName=~'$interface'}[$__rate_interval])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Unicast packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
     "repeat": "interface",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(ifHCInUcastPkts{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "In"
      },
      {
       "expr": "rate(ifHCOutUcastPkts{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Broadcast packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
     "repeat": "interface",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(ifHCInBroadcastPkts{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval]) or rate(ifInBroadcastPkts{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "In"
      },
      {
       "expr": "rate(ifHCOutBroadcastPkts{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval]) or rate(ifOutBroadcastPkts{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Multicast packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
     "repeat": "interface",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(ifHCInMulticastPkts{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval]) or rate(ifInMulticastPkts{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "In"
      },
      {
       "expr": "rate(ifHCOutMulticastPkts{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval]) or rate(ifOutMulticastPkts{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval]) ",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "repeat": "interface",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(ifInErrors{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "In"
      },
      {
       "expr": "rate(ifOutErrors{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Discards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
     "repeat": "interface",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(ifInDiscards{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "In discards"
      },
      {
       "expr": "rate(ifInUnknownProtos{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "In unknown protos"
      },
      {
       "expr": "rate(ifOutDiscards{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "Out discards"
      },
      {
       "expr": "rate(ifOutUnknownProtos{instance=\"$instance\",ifName=\"$interface\"}[$__rate_interval])",
       "legendFormat": "Out unknown protos"
      }
     ]
    }
   ]
  }
 ]
}